import turtle
tina = turtle.Turtle()
tina.shape("turtle")

tina.fillcolor("Navy")
tina.begin_fill()
tina.right(90)
tina.forward(50)
tina.right(90)
tina.forward(30)
tina.right(90)
tina.forward(90)
tina.right(90)
tina.forward(30)
tina.right(90)
tina.forward(40)
tina.end_fill()

tina.fillcolor("blue")
tina.begin_fill()
tina.left(180)
tina.forward(5)
tina.left(90)
tina.forward(10)
tina.left(90)
tina.forward(5)
tina.left(90)
tina.forward(10)
tina.end_fill()

tina.right(90)
tina.forward(50)

tina.left(90)
tina.forward(60)
tina.left(90)
tina.forward(110)
tina.left(90)
tina.forward(120)
tina.left(90)
tina.forward(110)
tina.left(90)
tina.forward(120)
tina.left(90)
tina.forward(55)
tina.left(90)

tina.pencolor("white")
tina.forward(5)  

tina.fillcolor("yellow")
tina.pencolor("black")
tina.begin_fill()
tina.forward(50)
tina.right(90)
tina.forward(45)
tina.right(90)
tina.forward(50)
tina.right(90)
tina.forward(45)
tina.end_fill()

tina.right(90)
tina.forward(25)
tina.right(90)
tina.forward(45)
tina.left(90)
tina.forward(25)
tina.left(90)
tina.forward(22.5)
tina.left(90)
tina.forward(50)

tina.pencolor("white")
tina.forward(5)
tina.pencolor("black")
tina.left(90)
tina.forward(32.5)

tina.fillcolor("red")
tina.begin_fill()
tina.left(45)
tina.forward(85)
tina.left(90)
tina.forward(85)
tina.end_fill()

tina.left(180)

tina.fillcolor("green")
tina.begin_fill()
tina.forward(45)
tina.left(45)
tina.forward(25)
tina.left(90)
tina.forward(10)
tina.left(90)
tina.forward(32)
tina.end_fill()
    
